# Generated by Django 5.1.2 on 2024-11-01 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_facebook_alter_blog_github_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='descricao',
            new_name='subnome',
        ),
    ]
