# Generated by Django 5.1.2 on 2024-11-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_descricao_blog_subnome'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='descricao',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subnome',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
